params:  
  seed: 42
  
  env:
    clip_observations: 5.0
    clip_actions: 2.0
  
  algo:
    name: sac
  
  model:
    name: soft_actor_critic
  
  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.5  # Encourage more initial exploration
    mlp:
      units: [512, 512, 512]  # Slightly larger networks help SAC stability
      activation: elu
      d2rl: False
      initializer:
        name: default
    log_std_bounds: [-5, 2]
    
  load_checkpoint: False
  load_path: ''
  
  config:
    name: cartpole_2_sac
    env_name: rlgpu
    multi_gpu: False
    normalize_input: False
    reward_shaper:
      scale_value: 1.0
    
    # SAC settings
    init_alpha: 0.02
    alpha_lr: 3e-4
    actor_lr: 3e-5
    critic_lr: 3e-4
    critic_tau: 0.005  # Polyak averaging, recommended for SAC
    batch_size: 256
    learnable_temperature: False
    
    # Training parameters
    max_epochs: 10000
    save_best_after: 50
    save_frequency: 1000
    gamma: 0.99
    tau: 0.005
    
    # Learning process
    num_seed_steps: 2000
    num_warmup_steps: 2000
    replay_buffer_size: 2000000
    
    # Environment setup
    num_actors: 1024  # Adjust to hardware capabilities
    
    # Device settings
    device: 'cuda:0'
    device_name: 'cuda:0'
    
    # Other settings
    ppo: False
    mixed_precision: False
    grad_norm: 1.0
    truncate_grads: True
    critic_coef: 1.0
    use_diagnostics: True
    bounds_loss_coef: 0.001  # mild regularization, avoids excessive penalty
    bound_loss_type: "regularisation"
    multi_step: 1  # Start with single-step updates for SAC
    
  env_cfg:
    rew_scale_alive: 2
    rew_scale_pole_angle: 5
    rew_scale_cart_vel: 0.00
    rew_scale_pole_vel: 0.00
    rew_scale_pole_straight: 0.0
    rew_scale_pole_upwards: 1
    rew_scale_exp_vel: 0
    vel_scale_factor: 14
    rew_scale_cart_center: 0.5
    rew_scale_bonus_first: 100
    rew_scale_bonus_second: 200
    rew_scale_bonus_third: 300